name: workflow.test

on:
  push:
    branches:
      - main

jobs:
  job-teste:
    runs-on: ubuntu-latest
    steps:
      - name: Print boas vindas
        run: echo "Usando rep ${{ github.repository }} !"

